---
driver:
  name: dokken
  chef_version: current
  ports:
    - '3000:3001'
    - '80:8080'

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init

suites:
  - name: deploy_tracks
    run_list:
      - recipe[apt::default]
      - recipe[tar::default]
      - recipe[deploy_tracks::default]
